var ccb_resources = [
    {type:'image', src:"bg-menu.png"},
    {type:'image', src:"board.png"},
    {type:'image', src:"ui.png"},
    {type:'plist', src:"ui.plist"},
    {type:'ccbi', src:"node/jump1.ccbi"},
    {type:'ccbi', src:"layer/pause.ccbi"},
    {type:'image', src:"icon-120.png"},
    {type:'ccbi', src:"node/1-4.ccbi"},
    {type:'ccbi', src:"node/1-3.ccbi"},
    {type:'ccbi', src:"node/1-2.ccbi"},
    {type:'ccbi', src:"node/1-1.ccbi"},
    {type:'image', src:"icon-114.png"},
    {type:'image', src:"demon1.png"},
    {type:'image', src:"bg-sky.png"},
    {type:'ccbi', src:"node/down1.ccbi"},
    {type:'plist', src:"jump-1.plist"},
    {type:'ccbi', src:"layer/gameover-single.ccbi"},
    {type:'image', src:"jump-1.png"},
    {type:'ccbi', src:"layer/mainmenu.ccbi"},
    {type:'ccbi', src:"layer/stage-single.ccbi"},
    {type:'plist', src:"demon1.plist"},
    {type:'image', src:"bg-black.png"},
    {type:'plist', src:"board.plist"},
];
